  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/assets/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/assets/js/bootstrap.min.js"></script>
  </body>
</html>
<?php
  /**
   * footer.inc - Global Footer file.
   * Akin to Site.Master in ASP.NET
   * 
   * PHP 7.1.7-1+ubuntu14.04.1+deb.sury.org+1
   * 
   * @author Robert Cato <saiwolf@swmnu.net>
   * @license https://opensource.org/licenses/mit-license.php MIT
   * 
   **/
?>